---
- name:  Create {{ az_secgroup_name }} Security Group on {{ az_region }}
  azure_rm_securitygroup:
    resource_group: "{{ az_resourcegroup_name }}"
    name: "{{ az_secgroup_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 100
        direction: Inbound
      - name: Http
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 103
        direction: Inbound
  run_once: yes

- name: Create NICs
  azure_rm_networkinterface:
    resource_group: "{{ az_resourcegroup_name }}"
    name: "nic-{{ az_scope }}-{{ item }}"
    virtual_network: "{{ az_virtualnet_name }}"
    subnet: "{{ az_subnet_name }}"
    security_group: "{{ az_secgroup_name }}"
    ip_configurations:
      - public_ip_address_name: "{{ az_scope }}-{{ item }}"
      - name: "{{ az_scope }}-{{ item }}"
        load_balancer_backend_address_pools:
          - name: "{{ az_loadbalancer_name }}-web-srv"
            load_balancer: "{{ az_loadbalancer_name }}"
  with_sequence: count="{{az_count}}" 

- name: "Create Virtual Machines"
  azure_rm_virtualmachine:
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    availability_set: "{{ az_availabilitysets_name }}"
    name: "{{ az_scope }}-{{ item }}"
    vm_size: "{{ az_vm_size }}"
    os_type: "{{ az_os_type_vm }}"
    storage_account_name: "{{ az_storageaccount_name }}"
    network_interface_names: "nic-{{ az_scope }}-{{ item }}"
    ssh_password_enabled: no
    admin_username: "{{ ssh_username }}"
    ssh_public_keys:
      - path: "/home/{{ ssh_username }}/.ssh/authorized_keys"
        key_data: "{{ ssh_key }}"    
    managed_disk_type: "{{ az_managed_disk_type }}"
    image:
      offer: "{{ az_image_offer }}"
      publisher: "{{ az_image_publisher }}"
      sku: "{{ az_image_sku }}"
      version: "{{ az_image_version }}"
    tags:
      purpose: "{{ az_environment }}"
      application: "{{ az_application }}"
      os: "{{ az_os_type_vm }}"
  async: 1
  poll: 0
  with_sequence: count="{{az_count}}" 
